version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
# registries:
#   python:
#     type: python-index
#     url: https://example.com/_packaging/my-feed/pypi/example
#     replaces-base: true